// travel_request_data.dart
import 'package:desktop_test/tables/table_query.dart';

/// Base 13 entries to clone from
final List<TravelRequest> _baseRequests = [
  TravelRequest(
    sn: 1,
    qId: 'Q2025001',
    entryDate: '2025-01-01',
    ledgerName: 'XYZ Tours',
    purpose: 'tkt',
    travelDate: '2025-01-15',
    returnDate: '2025-02-01',
    from: 'KTM',
    to: 'DOH',
    noOfPax: 2,
    qDays: 10,
    airlines: 'Thai Air',
    paxName: 'Maya Tamang',
    agent: 'ONTA',
    tNumber: 'KTM-DOH001',
    tStatus: 'cancelled',
    remarks: 'OK',
  ),
  TravelRequest(
    sn: 2,
    qId: 'Q2025002',
    entryDate: '2025-01-02',
    ledgerName: 'XTZ Tours',
    purpose: 'pb',
    travelDate: '2025-01-25',
    returnDate: '2025-02-10',
    from: 'KTM',
    to: 'IND',
    noOfPax: 1,
    qDays: 15,
    airlines: 'Qatar Airways',
    paxName: 'Merin Raj',
    agent: 'ONTA',
    tNumber: 'KTM-IND002',
    tStatus: 'processing',
    remarks: 'OK',
  ),
  TravelRequest(
    sn: 3,
    qId: 'Q2025003',
    entryDate: '2025-01-03',
    ledgerName: 'ABC Tours',
    purpose: 'refund',
    travelDate: '2025-02-01',
    returnDate: '2025-03-20',
    from: 'KTM',
    to: 'CHI',
    noOfPax: 6,
    qDays: 20,
    airlines: 'Etihad Airways',
    paxName: 'Ram Yadav',
    agent: 'ONTA',
    tNumber: 'KTM-CHI223',
    tStatus: 'confirmed',
    remarks: 'OK',
  ),
  TravelRequest(
    sn: 4,
    qId: 'Q2025004',
    entryDate: '2025-01-04',
    ledgerName: 'Eagle Tours',
    purpose: 'reissue',
    travelDate: '2025-02-01',
    returnDate: '2025-02-15',
    from: 'KTM',
    to: 'AUS',
    noOfPax: 5,
    qDays: 15,
    airlines: 'QatarAirways',
    paxName: 'Roshan Yakpal',
    agent: 'ONTA',
    tNumber: 'KTM-AUS096',
    tStatus: 'processing',
    remarks: 'OK',
  ),
  TravelRequest(
    sn: 5,
    qId: 'Q2025005',
    entryDate: '2025-01-05',
    ledgerName: 'XYZ Tours',
    purpose: 'credit',
    travelDate: '2025-02-05',
    returnDate: '2025-02-25',
    from: 'KTM',
    to: 'HGK',
    noOfPax: 3,
    qDays: 20,
    airlines: 'Sinapore Airways',
    paxName: 'Kusal Bhurtel',
    agent: 'ONTA',
    tNumber: 'KTM-HGK214',
    tStatus: 'credit',
    remarks: 'OK',
  ),
  TravelRequest(
    sn: 6,
    qId: 'Q2025006',
    entryDate: '2025-01-06',
    ledgerName: 'BTM Tours',
    purpose: 'group',
    travelDate: '2025-02-05',
    returnDate: '2025-03-05',
    from: 'KTM',
    to: 'USA',
    noOfPax: 5,
    qDays: 30,
    airlines: 'Air India',
    paxName: 'Shiva Khanal',
    agent: 'ONTA',
    tNumber: 'KTM-DOH001',
    tStatus: 'pending',
    remarks: 'OK',
  ),
  TravelRequest(
    sn: 7,
    qId: 'Q2025007',
    entryDate: '2025-01-07',
    ledgerName: 'Your travel',
    purpose: 'market',
    travelDate: '2025-02-05',
    returnDate: '2025-03-05',
    from: 'KTM',
    to: 'USA',
    noOfPax: 5,
    qDays: 30,
    airlines: 'Air India',
    paxName: 'Rita Khanal',
    agent: 'ONTA',
    tNumber: 'KTM-USA530',
    tStatus: 'market',
    remarks: 'OK',
  ),
  TravelRequest(
    sn: 8,
    qId: 'Q2025008',
    entryDate: '2025-01-08',
    ledgerName: 'Hello Tour',
    purpose: 'fare',
    travelDate: '2025-02-06',
    returnDate: '2025-02-22',
    from: 'KTM',
    to: 'SIG',
    noOfPax: 2,
    qDays: 16,
    airlines: 'Turkish Airlines',
    paxName: 'Ram Pokharel',
    agent: 'ONTA',
    tNumber: 'KTM-USA531',
    tStatus: 'confirmed',
    remarks: 'OK',
  ),
  TravelRequest(
    sn: 9,
    qId: 'Q2025009',
    entryDate: '2025-01-08',
    ledgerName: 'XYZ Tour',
    purpose: 'group',
    travelDate: '2025-02-08',
    returnDate: '2025-02-30',
    from: 'KTM',
    to: 'MAL',
    noOfPax: 6,
    qDays: 22,
    airlines: 'Air India',
    paxName: 'Hari Koju',
    agent: 'ONTA',
    tNumber: 'KTM-MAL963',
    tStatus: 'pending',
    remarks: 'OK',
  ),
  TravelRequest(
    sn: 10,
    qId: 'Q2025010',
    entryDate: '2025-01-08',
    ledgerName: 'ABC Tour',
    purpose: 'tkt',
    travelDate: '2025-02-08',
    returnDate: '2025-03-01',
    from: 'KTM',
    to: 'SPN',
    noOfPax: 3,
    qDays: 23,
    airlines: 'Turkish Airlines',
    paxName: 'Ranjan Baidya',
    agent: 'ONTA',
    tNumber: 'KTM-SPN785',
    tStatus: 'cancelled',
    remarks: 'OK',
  ),
  TravelRequest(
    sn: 11,
    qId: 'Q2025011',
    entryDate: '2025-01-09',
    ledgerName: 'Eagles Tour',
    purpose: 'tkt',
    travelDate: '2025-02-10',
    returnDate: '2025-03-12',
    from: 'KTM',
    to: 'FRC',
    noOfPax: 1,
    qDays: 32,
    airlines: 'Qatar Airways',
    paxName: 'Sita Srestha',
    agent: 'ONTA',
    tNumber: 'KTM-FRC142',
    tStatus: 'cancelled',
    remarks: 'OK',
  ),
  TravelRequest(
    sn: 12,
    qId: 'Q2025012',
    entryDate: '2025-01-09',
    ledgerName: 'Rombhus Tour',
    purpose: 'credit',
    travelDate: '2025-02-10',
    returnDate: '2025-03-14',
    from: 'KTM',
    to: 'AUS',
    noOfPax: 5,
    qDays: 34,
    airlines: 'Etihad Airways',
    paxName: 'Muskan Shrestha',
    agent: 'ONTA',
    tNumber: 'KTM-AUS325',
    tStatus: 'confirmed',
    remarks: 'OK',
  ),
  TravelRequest(
    sn: 13,
    qId: 'Q2025013',
    entryDate: '2025-01-09',
    ledgerName: 'Hamro Tour',
    purpose: 'reissue',
    travelDate: '2025-02-10',
    returnDate: '2025-03-16',
    from: 'KTM',
    to: 'DUB',
    noOfPax: 8,
    qDays: 36,
    airlines: 'Thai Air',
    paxName: 'Sajan Raj Sapkota',
    agent: 'ONTA',
    tNumber: 'KTM-DUB974',
    tStatus: 'processing',
    remarks: 'OK',
  ),
];

/// Generate 100 entries by cloning base requests
final List<TravelRequest> travelRequests = List.generate(100, (index) {
  final template = _baseRequests[index % _baseRequests.length];
  return TravelRequest(
    sn: index + 1,
    qId: 'Q2025${(index + 1).toString().padLeft(4, '0')}',
    entryDate: template.entryDate,
    ledgerName: template.ledgerName,
    purpose: template.purpose,
    travelDate: template.travelDate,
    returnDate: template.returnDate,
    from: template.from,
    to: template.to,
    noOfPax: template.noOfPax,
    qDays: template.qDays,
    airlines: template.airlines,
    paxName: template.paxName,
    agent: template.agent,
    tNumber: template.tNumber,
    tStatus: template.tStatus,
    remarks: template.remarks,
  );
});
